name: Github Pages

on:
  push:
    branches:
      - development

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target-branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{secrets.PAGES}}
